### ISSUE TITLE
scelta seleniumwire

### ISSUE THREAD

**Issue by Bbalduzz** [Ghost6446/StreamingCommunity_scraper#4]
Ciao! Ottimo tool 👍🏻 , volevo solo chiederti perchè hai scelto di utilizzare seleniumwire al posto di fare delle semplici richieste http

**Comment by Ghost6446** [comment]
Ora guardanto il tuo ultimo lavoro capisco la domanda per la richiesta.

Complimenti per aver trovato un api, 3 mesi fa non l'avevo notata 😂😂, sarebbe stato molto più facile.

**Comment by Bbalduzz** [comment]
Dai perfetto, ero solo curioso perche' comunque funziona molto bene.
Grazie per la spiegazione :))

**Comment by Ghost6446** [comment]
Di neinte
